### ISSUE TITLE
Removing Ingredient's doesn't work

### ISSUE THREAD

**Issue by MarshMello0** [grantlmul/SMEMT#2]
I can seem to add ingredients fine but when it comes to removing them it doesn't work.

There is a `Exception thrown: 'System.ArgumentOutOfRangeException' in mscorlib.dll` but not too sure where that is.

**Comment by MarshMello0** [comment]
So you seem to be adding to a list of `Recipe`'s but when you come to your remove buttons you are not removing them from that list, just removing them from the UI if I'm correct.

**Comment by MarshMello0** [comment]
Fixed and created a pull request #3

**Comment by grantlmul** [comment]
Merged.
